#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

// Send all errors to stderr
ini_set('display_errors', 'stderr');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

Yii::setAlias('@cebe/composer/bower', __DIR__);

$application = new yii\console\Application([
    'id' => 'yii-console',
    'basePath' => __DIR__,
    'controllerNamespace' => 'cebe\composer\bower\commands',
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
            'cachePath' => '@app/cache'
        ]
    ]
]);

$exitCode = $application->run();
exit($exitCode);
